// Generated by gencpp from file comm/day4msg.msg
// DO NOT EDIT!


#ifndef COMM_MESSAGE_DAY4MSG_H
#define COMM_MESSAGE_DAY4MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Twist.h>

namespace comm
{
template <class ContainerAllocator>
struct day4msg_
{
  typedef day4msg_<ContainerAllocator> Type;

  day4msg_()
    : time(0.0)
    , positon()
    , velocity()  {
    }
  day4msg_(const ContainerAllocator& _alloc)
    : time(0.0)
    , positon(_alloc)
    , velocity(_alloc)  {
  (void)_alloc;
    }



   typedef float _time_type;
  _time_type time;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _positon_type;
  _positon_type positon;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::comm::day4msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm::day4msg_<ContainerAllocator> const> ConstPtr;

}; // struct day4msg_

typedef ::comm::day4msg_<std::allocator<void> > day4msg;

typedef boost::shared_ptr< ::comm::day4msg > day4msgPtr;
typedef boost::shared_ptr< ::comm::day4msg const> day4msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm::day4msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm::day4msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm::day4msg_<ContainerAllocator1> & lhs, const ::comm::day4msg_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.positon == rhs.positon &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm::day4msg_<ContainerAllocator1> & lhs, const ::comm::day4msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm::day4msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm::day4msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm::day4msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm::day4msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm::day4msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm::day4msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm::day4msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4febcd00129bcc42354cebe4c20dacb3";
  }

  static const char* value(const ::comm::day4msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4febcd00129bcc42ULL;
  static const uint64_t static_value2 = 0x354cebe4c20dacb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm::day4msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm/day4msg";
  }

  static const char* value(const ::comm::day4msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm::day4msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 time\n"
"geometry_msgs/Twist positon\n"
"geometry_msgs/Twist velocity\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::comm::day4msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm::day4msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.positon);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct day4msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm::day4msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm::day4msg_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
    s << indent << "positon: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.positon);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MESSAGE_DAY4MSG_H
