// Generated by gencpp from file comm/test.msg
// DO NOT EDIT!


#ifndef COMM_MESSAGE_TEST_H
#define COMM_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <comm/testRequest.h>
#include <comm/testResponse.h>


namespace comm
{

struct test
{

typedef testRequest Request;
typedef testResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test
} // namespace comm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm::test > {
  static const char* value()
  {
    return "0e94547baedd4802a73be38202225d5a";
  }

  static const char* value(const ::comm::test&) { return value(); }
};

template<>
struct DataType< ::comm::test > {
  static const char* value()
  {
    return "comm/test";
  }

  static const char* value(const ::comm::test&) { return value(); }
};


// service_traits::MD5Sum< ::comm::testRequest> should match
// service_traits::MD5Sum< ::comm::test >
template<>
struct MD5Sum< ::comm::testRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm::test >::value();
  }
  static const char* value(const ::comm::testRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm::testRequest> should match
// service_traits::DataType< ::comm::test >
template<>
struct DataType< ::comm::testRequest>
{
  static const char* value()
  {
    return DataType< ::comm::test >::value();
  }
  static const char* value(const ::comm::testRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm::testResponse> should match
// service_traits::MD5Sum< ::comm::test >
template<>
struct MD5Sum< ::comm::testResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm::test >::value();
  }
  static const char* value(const ::comm::testResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm::testResponse> should match
// service_traits::DataType< ::comm::test >
template<>
struct DataType< ::comm::testResponse>
{
  static const char* value()
  {
    return DataType< ::comm::test >::value();
  }
  static const char* value(const ::comm::testResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_MESSAGE_TEST_H
