// Generated by gencpp from file comm/testResponse.msg
// DO NOT EDIT!


#ifndef COMM_MESSAGE_TESTRESPONSE_H
#define COMM_MESSAGE_TESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm
{
template <class ContainerAllocator>
struct testResponse_
{
  typedef testResponse_<ContainerAllocator> Type;

  testResponse_()
    : c(0.0)  {
    }
  testResponse_(const ContainerAllocator& _alloc)
    : c(0.0)  {
  (void)_alloc;
    }



   typedef float _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::comm::testResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm::testResponse_<ContainerAllocator> const> ConstPtr;

}; // struct testResponse_

typedef ::comm::testResponse_<std::allocator<void> > testResponse;

typedef boost::shared_ptr< ::comm::testResponse > testResponsePtr;
typedef boost::shared_ptr< ::comm::testResponse const> testResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm::testResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm::testResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm::testResponse_<ContainerAllocator1> & lhs, const ::comm::testResponse_<ContainerAllocator2> & rhs)
{
  return lhs.c == rhs.c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm::testResponse_<ContainerAllocator1> & lhs, const ::comm::testResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm::testResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm::testResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm::testResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm::testResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm::testResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm::testResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm::testResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "faa31482b3d9d0ca352e3be1282b0471";
  }

  static const char* value(const ::comm::testResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfaa31482b3d9d0caULL;
  static const uint64_t static_value2 = 0x352e3be1282b0471ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm::testResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm/testResponse";
  }

  static const char* value(const ::comm::testResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm::testResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 c\n"
;
  }

  static const char* value(const ::comm::testResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm::testResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct testResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm::testResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm::testResponse_<ContainerAllocator>& v)
  {
    s << indent << "c: ";
    Printer<float>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MESSAGE_TESTRESPONSE_H
